---
- name: Build Docker image to build IDA NRTS binaries
  remote_user: ec2-user
  # become_method: sudo
  # become_user: root
  hosts: default

  tasks:

  - name: install make
    yum:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    become: true
    loop:
      - openssh
      - make
      - zlib-devel
      - wget
      - gcc
      - ncurses-devel
      - libxml2-devel
      - tcsh
      - vim
      - ntp
      - git
      - lsof
      - man-pages
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - iftop
      - xorriso
      - tree
  
  # - name: install pip 
  #   yum:
  #     name: python-pip
  #     state: latest

  # - name: install aws cli
  #   shell: pip install awscli 

  # - name: check aws cli version
  #   shell: aws --version

