---
- name: Provision AMI image with IDA NRTS
  remote_user: ec2-user
  hosts: default
  vars:
    target_major_version: "{{ ansible_facts['distribution_major_version'] }}"
    target_family: "{{ ansible_facts['os_family']|lower }}"
    target: "{{ target_family }}{{ target_major_version }}"

  tasks:
    - import_role:
        name: hub-base
      vars:
        nrts_src_version: ""  # currently unused, but should in future, pull from github "release" version
        system_hostname: nrtshub
        home_root: "{{ home_location }}"
        nrts_home_dir : "{{ home_location }}/nrts"
        git_src_branch: "{{ git_branch }}"
