---
- name: Build Docker image to build IDA NRTS binaries
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  hosts: default

  tasks:

  - name: install make
    yum:
      name: make
      state: latest
  - name: install git
    yum:
      name: git
      state: latest
  - name: install tcsh
    yum:
      name: tcsh
      state: latest
  - name: install openssh
    yum:
      name: openssh
      state: latest
  - name: install gcc
    yum:
      name: gcc
      state: latest
  - name: install zlib-devel
    yum:
      name: zlib-devel
      state: latest
  - name: install ncurses-devel
    yum:
      name: ncurses-devel
      state: latest
  - name: install libxml2-devel
    yum:
      name: libxml2-devel
      state: latest

  - name: check python version
    shell: |
        python --version
        aws --version

